version: '3.9'

services:
  php-env:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
  mysql_db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306

    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: "0.0.0.0"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
